Revert "Fix compile warning with -Wshadow"
This reverts commit 1f5e971f77cdb3a06185b7e134549cc52906da68.

See #1306; the previous commit caused an error with -Wpedantic:

yaml-cpp/include/yaml-cpp/emitterstyle.h:13:2: error: extra ‘;’ [-Wpedantic]

Since the original commit was to resolve warnings, reverting and the OP can produce a new one that fixes this issue.